# Handle Categorical Variables - One-Hot Encoding and Label Encoder

In [10]:
# Load the dataset
import pandas as pd

df = pd.read_csv(r"K:\End-to-End-Airbnb-Price-Prediction-ML-System\data\raw\cleaned_airbnb_data.csv")
df.head()

,log_price,property_type,room_type,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_has_profile_pic,...,host_response_rate,instant_bookable,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds,amenities_count,host_years
0,5.010635,Apartment,Entire home/apt,3,1.0,Real Bed,strict,1,NYC,1,...,100.0,0,40.696524,-73.991617,2,100.0,1.0,1.0,9,13.0
1,5.129899,Apartment,Entire home/apt,7,1.0,Real Bed,strict,1,NYC,1,...,100.0,1,40.766115,-73.989040,6,93.0,3.0,3.0,15,8.0
2,4.976734,Apartment,Entire home/apt,5,1.0,Real Bed,moderate,1,NYC,1,...,100.0,1,40.808110,-73.943756,10,92.0,1.0,3.0,19,9.0
3,6.620073,House,Entire home/apt,4,1.0,Real Bed,flexible,1,SF,1,...,100.0,0,37.772004,-122.431619,0,96.0,2.0,2.0,15,10.0
4,4.744932,Apartment,Entire home/apt,2,1.0,Real Bed,moderate,1,DC,1,...,100.0,1,38.925627,-77.034596,4,40.0,0.0,1.0,12,10.0

In [11]:
# Categorical columns
df.select_dtypes(include='object').columns

Index(['property_type', 'room_type', 'bed_type', 'cancellation_policy',
       'city'],
      dtype='object')

In [12]:
# Check the how many unique property type we have in our dataset
df["property_type"].nunique()

35

In [13]:
# Handels Property Type column by keeping only top 10 types and remaing will be other category
df['property_type'].value_counts().head(11)

property_type
Apartment          49003
House              16511
Condominium         2658
Townhouse           1692
Loft                1244
Other                607
Guesthouse           498
Bed & Breakfast      462
Bungalow             366
Villa                179
Dorm                 142
Name: count, dtype: int64

In [14]:
# Top 10 Property Types
top_property_types = df['property_type'].value_counts().nlargest(11).index

# Replace the Remaining Categories with "Other"
df['property_type'] = df['property_type'].apply(
    lambda x: x if x in top_property_types else 'Other'
)

# Check the Result
df['property_type'].value_counts()

property_type
Apartment          49003
House              16511
Condominium         2658
Townhouse           1692
Other               1356
Loft                1244
Guesthouse           498
Bed & Breakfast      462
Bungalow             366
Villa                179
Dorm                 142
Name: count, dtype: int64

In [15]:
# Check the how many unique Cities we have in our dataset
df["city"].nunique()

6

In [17]:
df["city"].value_counts()

city
NYC        32349
LA         22453
SF          6434
DC          5688
Chicago     3719
Boston      3468
Name: count, dtype: int64

In [18]:
df["room_type"].value_counts()

room_type
Entire home/apt    41310
Private room       30638
Shared room         2163
Name: count, dtype: int64

In [19]:
df["bed_type"].value_counts()

bed_type
Real Bed         72028
Futon              753
Pull-out Sofa      585
Airbed             477
Couch              268
Name: count, dtype: int64

In [20]:
df["cancellation_policy"].value_counts()

cancellation_policy
strict             32374
flexible           22545
moderate           19063
super_strict_30      112
super_strict_60       17
Name: count, dtype: int64

In [21]:
# Convert categorical columns to numerical 
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['room_type'] = le.fit_transform(df['room_type'])
df['bed_type'] = le.fit_transform(df['bed_type'])
df['cancellation_policy'] = le.fit_transform(df['cancellation_policy'])

df[["room_type","bed_type","cancellation_policy"]].head(10)

   room_type  bed_type  cancellation_policy
0          0         4                    2
1          0         4                    2
2          0         4                    1
3          0         4                    0
4          0         4                    1
5          1         4                    2
6          0         4                    1
7          0         4                    1
8          1         4                    1
9          1         4                    1

In [26]:
#One Hot Encode Categorical Columns (by get_dummies method)
categorical_cols = df.select_dtypes(include='object').columns

df = pd.get_dummies(df, columns=categorical_cols, drop_first=False, dtype=int)

df.head(10)

,log_price,room_type,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,host_has_profile_pic,host_identity_verified,host_response_rate,...,property_type_Loft,property_type_Other,property_type_Townhouse,property_type_Villa,city_Boston,city_Chicago,city_DC,city_LA,city_NYC,city_SF
0,5.010635,0,3,1.0,4,2,1,1,1,100.0,...,0,0,0,0,0,0,0,0,1,0
1,5.129899,0,7,1.0,4,2,1,1,0,100.0,...,0,0,0,0,0,0,0,0,1,0
2,4.976734,0,5,1.0,4,1,1,1,1,100.0,...,0,0,0,0,0,0,0,0,1,0
3,6.620073,0,4,1.0,4,0,1,1,1,100.0,...,0,0,0,0,0,0,0,0,0,1
4,4.744932,0,2,1.0,4,1,1,1,1,100.0,...,0,0,0,0,0,0,1,0,0,0
5,4.442651,1,2,1.0,4,2,1,1,1,100.0,...,0,0,0,0,0,0,0,0,0,1
6,4.418841,0,3,1.0,4,1,1,1,0,100.0,...,0,0,0,0,0,0,0,1,0,0
7,4.787492,0,2,1.0,4,1,1,1,1,100.0,...,0,0,0,0,0,0,0,1,0,0
8,4.787492,1,2,1.0,4,1,1,1,0,100.0,...,0,0,0,0,0,0,0,0,0,1
9,3.583519,1,2,1.0,4,1,1,1,0,100.0,...,0,0,0,0,0,0,0,1,0,0

In [27]:
df.to_csv(r"K:\End-to-End-Airbnb-Price-Prediction-ML-System\data\raw\train.csv",index = False)